version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps):"

  - package-ecosystem: "pip"
    directory: "/services/api"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps):"

  - package-ecosystem: "pip"
    directory: "/services/worker"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps):"

  - package-ecosystem: "pip"
    directory: "/services/jupyter"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps):"
